import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export async function exportResultsAsPDF(
  matchPercentage: number,
  matchedSkills: string[],
  missingSkills: string[],
  improvedResume: string,
  recommendations: { role: string; company: string; matchPercentage: number; reason: string }[]
) {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = 210;
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // ── Header ──
  pdf.setFillColor(79, 70, 229);
  pdf.rect(0, 0, pageWidth, 35, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'bold');
  pdf.text('AI Resume Analysis Report', margin, 22);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Generated on ${new Date().toLocaleDateString()}`, margin, 30);
  y = 50;

  // ── Match Score ──
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Match Score', margin, y);
  y += 8;

  const scoreColor = matchPercentage >= 70 ? [34, 197, 94] : matchPercentage >= 40 ? [234, 179, 8] : [239, 68, 68];
  pdf.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  pdf.roundedRect(margin, y, 50, 18, 3, 3, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`${matchPercentage}%`, margin + 10, y + 12);
  pdf.setTextColor(100, 100, 100);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Resume-to-Job Match', margin + 55, y + 10);
  y += 30;

  // ── Matched Skills ──
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Matched Skills', margin, y);
  y += 7;

  let x = margin;
  matchedSkills.forEach((skill) => {
    const w = pdf.getTextWidth(skill) + 8;
    if (x + w > pageWidth - margin) { x = margin; y += 10; }
    pdf.setFillColor(220, 252, 231);
    pdf.roundedRect(x, y - 5, w, 8, 2, 2, 'F');
    pdf.setTextColor(22, 163, 74);
    pdf.setFontSize(9);
    pdf.text(skill, x + 4, y);
    x += w + 4;
  });
  y += 15;

  // ── Missing Skills ──
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Missing Skills', margin, y);
  y += 7;

  x = margin;
  missingSkills.forEach((skill) => {
    const w = pdf.getTextWidth(skill) + 8;
    if (x + w > pageWidth - margin) { x = margin; y += 10; }
    pdf.setFillColor(254, 226, 226);
    pdf.roundedRect(x, y - 5, w, 8, 2, 2, 'F');
    pdf.setTextColor(220, 38, 38);
    pdf.setFontSize(9);
    pdf.text(skill, x + 4, y);
    x += w + 4;
  });
  y += 20;

  // ── New Page for Improved Resume ──
  pdf.addPage();
  y = 20;

  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('AI-Improved Resume', margin, y);
  y += 10;

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(60, 60, 60);
  const resumeLines = pdf.splitTextToSize(improvedResume, contentWidth);
  resumeLines.forEach((line: string) => {
    if (y > 270) { pdf.addPage(); y = 20; }
    pdf.text(line, margin, y);
    y += 5;
  });

  // ── New Page for Job Recommendations ──
  pdf.addPage();
  y = 20;

  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Job & Company Recommendations', margin, y);
  y += 12;

  recommendations.forEach((rec) => {
    if (y > 250) { pdf.addPage(); y = 20; }
    pdf.setFillColor(245, 243, 255);
    pdf.roundedRect(margin, y - 5, contentWidth, 30, 3, 3, 'F');

    pdf.setTextColor(79, 70, 229);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(rec.role, margin + 5, y + 4);

    pdf.setTextColor(100, 100, 100);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(rec.company, margin + 5, y + 11);

    const scoreW = pdf.getTextWidth(`${rec.matchPercentage}%`) + 8;
    pdf.setFillColor(79, 70, 229);
    pdf.roundedRect(pageWidth - margin - scoreW - 5, y - 2, scoreW + 5, 10, 2, 2, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(10);
    pdf.text(`${rec.matchPercentage}%`, pageWidth - margin - scoreW, y + 6);

    pdf.setTextColor(80, 80, 80);
    pdf.setFontSize(9);
    const reasonLines = pdf.splitTextToSize(rec.reason, contentWidth - 10);
    pdf.text(reasonLines, margin + 5, y + 18);
    y += 38;
  });

  // ── Footer on all pages ──
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFillColor(245, 245, 245);
    pdf.rect(0, 285, pageWidth, 12, 'F');
    pdf.setTextColor(150, 150, 150);
    pdf.setFontSize(8);
    pdf.text('Generated by ResumeAI', margin, 292);
    pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, 292);
  }

  pdf.save('Resume_Analysis_Report.pdf');
}