import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileDown, Wand2 } from 'lucide-react';
import jsPDF from 'jspdf';

interface ImprovedResumeProps {
  content: string;
}

export function ImprovedResume({ content }: ImprovedResumeProps) {
  const handleDownload = () => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210;
    const margin = 15;
    const contentWidth = pageWidth - margin * 2;
    let y = 20;

    // Header
    pdf.setFillColor(79, 70, 229);
    pdf.rect(0, 0, pageWidth, 35, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(22);
    pdf.setFont('helvetica', 'bold');
    pdf.text('AI-Improved Resume', margin, 22);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Generated on ${new Date().toLocaleDateString()}`, margin, 30);
    y = 50;

    // Resume content
    pdf.setTextColor(40, 40, 40);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');

    const lines = content.split('\n');
    lines.forEach((line) => {
      if (y > 270) {
        pdf.addPage();
        y = 20;
      }

      // Make section headings bold
      if (
        line.includes('Summary') ||
        line.includes('Skills') ||
        line.includes('Experience') ||
        line.includes('Education') ||
        line.includes('Projects')
      ) {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(12);
        pdf.setTextColor(79, 70, 229);
      } else {
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(10);
        pdf.setTextColor(40, 40, 40);
      }

      const splitLines = pdf.splitTextToSize(line || ' ', contentWidth);
      splitLines.forEach((splitLine: string) => {
        if (y > 270) {
          pdf.addPage();
          y = 20;
        }
        pdf.text(splitLine, margin, y);
        y += 6;
      });
    });

    // Footer
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFillColor(245, 245, 245);
      pdf.rect(0, 285, pageWidth, 12, 'F');
      pdf.setTextColor(150, 150, 150);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Generated by ResumeAI', margin, 292);
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, 292);
    }

    pdf.save('Improved_Resume.pdf');
  };

  return (
    <Card className="p-6 animate-slide-up" style={{ animationDelay: '0.2s' }}>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold text-foreground flex items-center gap-2">
          <Wand2 className="h-5 w-5 text-accent" />
          AI-Improved Resume
        </h3>
        <Button size="sm" onClick={handleDownload} className="gap-1.5 bg-green-600 hover:bg-green-700">
          <FileDown className="h-4 w-4" />
          Download PDF
        </Button>
      </div>
      <div className="bg-muted/50 rounded-lg p-4 max-h-[400px] overflow-y-auto">
        <pre className="text-sm text-foreground whitespace-pre-wrap font-sans leading-relaxed">
          {content}
        </pre>
      </div>
    </Card>
  );
}